# -*- coding: utf-8 -*-
"""WhoAmI_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4ChfKbjnIbgM--N-9OarJuOGhrznqr_
"""

def WhoAmI():
  return ('lc3947')

